# Generated by Django 3.0.6 on 2020-07-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productID',
            new_name='productName',
        ),
    ]
