# Generated by Django 3.0.6 on 2020-07-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyProfile', '0002_auto_20200709_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='photos',
            name='short_description',
            field=models.TextField(default='test short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='short_description',
            field=models.TextField(default='test shot'),
            preserve_default=False,
        ),
    ]
