# Generated by Django 3.0.6 on 2020-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('verification', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
