# Generated by Django 3.1.6 on 2021-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_messages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
